### ISSUE TITLE
Atualizar registros JSON para novo padrão do BD

### ISSUE THREAD

**Issue by tiagoboeing** [computacaoUnisul/biblioteca-dos-cursos#20]
Como a estrutura do banco de dados foi alterada, nomes e relacionamentos, favor verificar e alterar os padrões no formato JSON. O arquivo que é utilizado atualmente é este: https://github.com/computacaoUnisul/biblioteca-dos-cursos/blob/master/db.json

Já está nos padrões e funcionando na aplicação. Quando alterar, favor atualizar esta issue para que as adequações no código do sistema sejam realizadas.

**Comment by rocha-rafael** [comment]
Ok, farei a alteração assim eu chegar em casa.

**Comment by tiagoboeing** [comment]
No resumo: seria mais tirar os prefixos das tabelas, com um CTRL + F e substituir. Verificar as alterações de relacionamentos, teve algumas. Tabela professores foi espelhada de usuários.

**Comment by rocha-rafael** [comment]
Já devia ter feito essa alteração, acabei esquecendo.
Bora profitar e croxxfitar

**Comment by rocha-rafael** [comment]
Rélou @tiagoboeing, atualizei os registros do BD, adequando-os as alterações do modelo.

Google Drive\Biblioteca da Computação - Engenharia de Software\Diagrama de Classes\db.json

Arquivo já validado.

**Comment by tiagoboeing** [comment]
Temmmmquiuuu, rodou lindamente my friend!

**Comment by rocha-rafael** [comment]
Wohoooooooooooooooo, bora Burpar
