### ISSUE TITLE
Registros do Banco de Dados para JSON

### ISSUE THREAD

**Issue by rocha-rafael** [computacaoUnisul/biblioteca-dos-cursos#3]

**Comment by tiagoboeing** [comment]
Arquivo JSON modelo:
https://github.com/tiagoboeing/meat-app-starter/blob/master/db.json

**Comment by tiagoboeing** [comment]
Alguma novidade?

**Comment by rocha-rafael** [comment]
Enviado o arquivo .JSON para a pasta do drive: Biblioteca da Computação - Engenharia de Software/Diagrama de Classes/biblioteca_cursos.json

**Comment by rocha-rafael** [comment]
Aguardando validação dos dados.

**Comment by tiagoboeing** [comment]
Precisa estar nos padrões de mongo DB, aí seria só a exportação do MySQL.
Este é o modelo: https://github.com/tiagoboeing/meat-app-starter/blob/master/db.json

**Comment by rocha-rafael** [comment]
Ok, irei adequar

**Comment by rocha-rafael** [comment]
Adequei ao molde do modelo passado, favor validar.
Arquivo foi atualizado no drive.

**Comment by tiagoboeing** [comment]
Quase... Fora dos padrões ainda.
![image](https://user-images.githubusercontent.com/3449932/38221311-3e1872f2-36b5-11e8-975d-466c740fdb27.png)

**Comment by tiagoboeing** [comment]
Seria tipo assim:

{
    "usuario":[
        {
            "usu_id":"1",
            "usu_nome":"Rafael",
            "usu_sobrenome":"Rocha",
            "usu_email":"rafael@gmail.com",
            "usu_status":"PENDENTE",
            "usu_tipousuario":"PROFESSOR",
            "usu_senha":"123",
            "usu_foto":"rafa.jpeg"
        },
        {
            "usu_id":"2",
            "usu_nome":"Fernando",
            "usu_sobrenome":"Abuss",
            "usu_email":"fernando.abuss@unisul.br",
            "usu_status":"PENDENTE",
            "usu_tipousuario":"PROFESSOR",
            "usu_senha":"123",
            "usu_foto":"abuss.png"
        }
    ]
}

**Comment by rocha-rafael** [comment]
Ok, vou ajustar

**Comment by rocha-rafael** [comment]
Dá um bizu lá pa noixxx

**Comment by tiagoboeing** [comment]
Cadastra uns alunos para testes. Professores, etc parece estar ok.
![image](https://user-images.githubusercontent.com/3449932/38221594-ba79c07a-36b6-11e8-8b4e-b58f8db323a8.png)

Pode validar o JSON aqui: https://jsonlint.com/

**Comment by rocha-rafael** [comment]
Beleza, vou fazer os outros cadastros

**Comment by rocha-rafael** [comment]
biblioteca_cursos.json **updated**, **validated**.
Disponível no drive.

**Os registros foram inseridos diretamente no .json, portanto, amanhã irei incluir os dados cadastrados no BD e atualizarei os arquivos .sql.**

**Comment by tiagoboeing** [comment]
Muito bom jovem, será super útil, se houver algum problema ao longo das consultas abrimos outra issue. Abração!

**Comment by tiagoboeing** [comment]
Favor desconsiderar o arquivo JSON do Google Drive e passar a utilizar o que se encontra no repositório caso necessário, este já está validado e funcionando na aplicação: https://github.com/computacaoUnisul/biblioteca-dos-cursos/blob/front-end/db.json
