### ISSUE TITLE
Estrutura da tabela de matérias

### ISSUE THREAD

**Issue by tiagoboeing** [computacaoUnisul/biblioteca-dos-cursos#32]
Desenvolvendo a consulta da API, percebi que precisaremos realizar modificações pequenas na **tabela materias** no banco de dados.

- Precisaremos incluir o campo url -> este campo terá o nome da matéria para url amigável.

A API deverá fornecer as matérias em ordem alfabética e com os relacionamentos já efetuados, ou seja, nome do professor por extenso e não apenas ID.
![image](https://user-images.githubusercontent.com/3449932/39708827-90921fde-51ee-11e8-87b0-f1acb8b30d60.png)

**Comment by leonardojcmay** [comment]
Certo, creio que deva ser necessário essa utilização da 'url' em outras tabelas, não só com matérias. Por exemplo colocar tbm em professores, cursos ....
