### ISSUE TITLE
Mais dados para consultas no JSON

### ISSUE THREAD

**Issue by tiagoboeing** [computacaoUnisul/biblioteca-dos-cursos#33]
Favor preencher o arquivo com mais dados, porém nos padrões dos últimos commits, pois foram realizadas adaptações, a tabela conteúdos é a mais importante no momento.

**[Neste commit](https://github.com/computacaoUnisul/biblioteca-dos-cursos/blob/31842552b1bff0333d3a1713bafdb4ecc31eb4bb/db.json)** o arquivo já está nos padrões.

**Comment by rocha-rafael** [comment]
Finalizado e disponibilizado no Google Drive.

Diagrama de classes > db.json

O mesmo foi validado.
